using ECCHackaton24.Feature.ImageFinder.Repositories;
using System.Web.Mvc;

namespace ECCHackaton24.Feature.ImageFinder.Controllers
{
    public class ImageFinderController: Controller
    {
        /// <summary>
        /// Search images in media library based on the tags generated by google AI
        /// </summary>
        /// <param name="searchKeywords"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult SearchMediaLibraryImage(string searchKeywords)
        {
            ImageFinderRepository repo = new ImageFinderRepository("sitecore_web_index");
            var result = repo.SearchMediaLibraryImage(searchKeywords);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}